# Generated by Django 5.2.17 on 2026-09-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="Throwaway portfolio-demo account. Never pays, never takes a real seat.",
            ),
        ),
    ]
