# Generated by Django 5.2.17 on 2026-09-23 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                (
                    "tagline",
                    models.CharField(
                        help_text="One line for the programme card.", max_length=200
                    ),
                ),
                ("description", models.TextField()),
                (
                    "outcomes",
                    models.TextField(
                        blank=True,
                        help_text='"What you will practise": one item per line.',
                    ),
                ),
                (
                    "photo_caption",
                    models.CharField(
                        blank=True,
                        help_text="Describes the photo, shown until a real one is added.",
                        max_length=120,
                    ),
                ),
                ("session_minutes", models.PositiveSmallIntegerField(default=75)),
                ("price_full_cents", models.PositiveIntegerField(default=24000)),
                ("instalment_cents", models.PositiveIntegerField(default=13000)),
                ("instalment_count", models.PositiveSmallIntegerField(default=2)),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("starts_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=90)),
                ("capacity", models.PositiveSmallIntegerField(default=20)),
                ("price_cents", models.PositiveIntegerField(default=3500)),
                ("zoom_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text='e.g. "November group".', max_length=80),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        help_text="Date and time of the first session."
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(default=12)),
                (
                    "zoom_url",
                    models.URLField(
                        blank=True,
                        help_text="Only shown to paid members, 15 minutes before each session.",
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, help_text="Open for new bookings."
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="catalog.program",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=160)),
                (
                    "summary",
                    models.TextField(blank=True, help_text='"What we\'ll work on".'),
                ),
                (
                    "exercise",
                    models.TextField(
                        blank=True, help_text='"Before the session" exercise.'
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="catalog.program",
                    ),
                ),
            ],
            options={
                "ordering": ["program", "number"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=75)),
                (
                    "recording_url",
                    models.URLField(
                        blank=True,
                        help_text="Unlisted YouTube link, added after the session.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Elena's notes after the session."
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="catalog.cohort",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="catalog.sessiontopic",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="sessiontopic",
            constraint=models.UniqueConstraint(
                fields=("program", "number"), name="unique_topic_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                fields=("cohort", "topic"), name="unique_session_topic"
            ),
        ),
    ]
