# Generated by Django 5.2.17 on 2026-09-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to show it on every program page.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_items",
                        to="catalog.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ item",
                "ordering": ["order", "pk"],
            },
        ),
    ]
