# Generated by Django 5.2.17 on 2026-09-23 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("type", models.CharField(max_length=100)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting payment"),
                            ("active", "Paid"),
                            ("expired", "Checkout expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                ("amount_paid_cents", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("full", "Pay in full"),
                            ("instalments", "Monthly instalments"),
                        ],
                        default="full",
                        max_length=12,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("instalments_paid", models.PositiveSmallIntegerField(default=0)),
                (
                    "payment_problem",
                    models.BooleanField(
                        default=False,
                        help_text="Set when a monthly instalment fails. Cleared when one succeeds.",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="catalog.cohort",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("user", "cohort"),
                        name="one_active_enrollment_per_cohort",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="catalog.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "session"), name="unique_session_completion"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkshopBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting payment"),
                            ("active", "Paid"),
                            ("expired", "Checkout expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                ("amount_paid_cents", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.workshop",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("user", "workshop"),
                        name="one_active_booking_per_workshop",
                    )
                ],
            },
        ),
    ]
