# Generated by Django 5.2.17 on 2026-09-23 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("catalog", "0002_faq_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist",
                        to="catalog.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist",
                        to="catalog.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "waitlist",
                "ordering": ["created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("program__isnull", False), ("workshop__isnull", True)
                            ),
                            models.Q(
                                ("program__isnull", True), ("workshop__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="waitlist_for_program_or_workshop",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("program__isnull", False)),
                        fields=("program", "email"),
                        name="one_waitlist_entry_per_program",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("workshop__isnull", False)),
                        fields=("workshop", "email"),
                        name="one_waitlist_entry_per_workshop",
                    ),
                ],
            },
        ),
    ]
